apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  labels:
    io.kompose.service: mall-monitor
  name: mall-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mall-monitor
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      labels:
        io.kompose.service: mall-monitor
    spec:
      containers:
        - env:
            - name: JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: TZ
              value: '"Asia/Shanghai"'
          image: mall/mall-monitor:1.0-SNAPSHOT
          name: mall-monitor
          ports:
            - containerPort: 8101
          resources: {}
          volumeMounts:
            - mountPath: /var/logs
              name: mall-monitor-claim0
      restartPolicy: Always
      volumes:
        - name: mall-monitor-claim0
          persistentVolumeClaim:
            claimName: mall-monitor-claim0
