apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
      nodePort: 9200
    - name: "9300"
      port: 9300
      targetPort: 9300
      nodePort: 9300
  type: NodePort
  selector:
    io.kompose.service: elasticsearch
