apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-data
  labels:
    io.kompose.service: minio-data

spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  nfs:
    path: /mydata/minio/data
    server: 10.100.6.145
##配置PV
