apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-log
  labels:
    io.kompose.service: nginx-log

spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  nfs:
    path: /mydata/nginx/log
    server: 10.100.6.145
##配置PV
