apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-data
  labels:
    io.kompose.service: rabbitmq-data

spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  nfs:
    path: /mydata/rabbitmq/data
    server: 10.100.6.145
##配置PV
