apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  labels:
    io.kompose.service: redis-slave1
  name: redis-slave1
spec:
  ports:
    - name: "6378"
      port: 6378
      targetPort: 6379
      nodePort: 6378
  type: NodePort
  selector:
    io.kompose.service: redis-slave1
