apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data
  labels:
    io.kompose.service: elasticsearch-data

spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  nfs:
    path: /mydata/elasticsearch/data
    server: 10.100.6.140
##配置PV
