apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-plugins
  labels:
    io.kompose.service: elasticsearch-plugins

spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  nfs:
    path: /mydata/elasticsearch/plugins
    server: 10.100.6.140
##配置PV
