apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logstash
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      labels:
        io.kompose.service: logstash
    spec:
      containers:
        - env:
            - name: TZ
              value: Asia/Shanghai
          image: logstash:7.8.1
          name: logstash
          ports:
            - containerPort: 4560
            - containerPort: 4561
            - containerPort: 4562
            - containerPort: 4563
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/logstash/pipeline/logstash.conf
              name: logstash-config-map
              subPath: logstash.conf
      restartPolicy: Always
      volumes:
        - name: logstash-config-map
          configMap:
            name: logstash-config
            items:
              - key: logstash-config
                path: logstash.conf
