apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  labels:
    io.kompose.service: minio
  name: minio
spec:
  ports:
    - name: "9002"
      port: 9002
      targetPort: 9000
      nodePort: 9002
  type: NodePort
  selector:
    io.kompose.service: minio
