apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-config
  labels:
    io.kompose.service: minio-config

spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  nfs:
    path: /mydata/minio/config
    server: 10.100.6.140
##配置PV
