apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  master.conf: |
    port=27017       #端口号
    fork=true        #以守护进程方式运行
    #logpath=/usr/local/mongodb/logs/mongodb.log  #日志文件
    logappend=true   #日志输出方式
    #dbpath=/usr/local/mongodb/data  #数据库位置
    maxConns=1024    #数据库最大连接数
    master=true      #主模式
    oplogSize=2048   #日志滚动，单位M
  slave.conf: |
    port=27018
    fork=true
    #logpath=/usr/local/mongodb/logs/mongodb.log
    logappend=true
    #dbpath=/usr/local/mongodb/data
    maxConns=1024
    slave=true                  #从模式
    source=10.100.6.140:27017  #指定主Mongodb
    autoresync=true             #自动同步
