apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  labels:
    io.kompose.service: mongo-slave
  name: mongo-slave
spec:
  ports:
    - name: "27018"
      port: 27018
      targetPort: 27017
      nodePort: 27018
  type: NodePort
  selector:
    io.kompose.service: mongo-slave
