apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-slave-config
data:
  slave.cnf: |+
    [mysqld]
    server_id=102
    binlog-ignore-db=mysql
    log-bin=replicas-mysql-slave-bin
    binlog_cache_size=1M
    binlog_format=mixed
    expire_logs_days=7
    slave_skip_errors=1062
    relay_log=replicas-mysql-relay-bin
    log_slave_updates=1
    read_only=1
    datadir = /var/lib/mysql
