apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-config
  labels:
    io.kompose.service: mysql-config

spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  nfs:
    path: /mydata/mysql/data/conf/my.cnf
    server: 10.100.6.140
##配置PV
