apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mysql-slave-claim0
  name: mysql-slave-claim0
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: default
  selector:
    matchLabels:
      io.kompose.service: mysql-slave-data
