apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mysql-claim1
  name: mysql-claim1
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: default
  selector:
    matchLabels:
      io.kompose.service: mysql-config
##配置PVC
