apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-slave2-log
  labels:
    io.kompose.service: mysql-slave2-log

spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  nfs:
    path: /mydata/mysql-slave2/log
    server: 10.100.6.140
##配置PV
