apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-html
  labels:
    io.kompose.service: nginx-html

spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  nfs:
    path: /mydata/nginx/html
    server: 10.100.6.140
##配置PV
