apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: redis-slave2
  name: redis-slave2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-slave2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: redis-slave2
    spec:
      containers:
        - args:
            - redis-server
            - --slaveof
            - redis
            - "6379"
            - --appendonly
            - "yes"
          image: redis:latest
          name: redis-slave2
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
status: {}
