apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  labels:
    io.kompose.service: mall-portal
  name: mall-portal
spec:
  ports:
    - name: "8085"
      port: 8085
      targetPort: 8085
      nodePort: 8085
  type: NodePort
  selector:
    io.kompose.service: mall-portal
